<?php

declare(strict_types=1);

namespace App\Services;

use App\Models\RecurringTransaction;
use Carbon\Carbon;
use Carbon\CarbonPeriod;
use Exception;
use Illuminate\Support\Facades\Log;

final class RecurringTransactionService
{
    public function generateFutureTransactions(RecurringTransaction $recurringTransaction, int $monthsAhead = 3): void
    {
        if (!$recurringTransaction->is_active) {
            return;
        }

        $period = $this->defineGenerationPeriod($recurringTransaction, $monthsAhead);

        collect($period)
            ->map(fn (Carbon $month) => $recurringTransaction->calculateExactDateForMonth($month))
            ->filter(fn (Carbon $date) => $recurringTransaction->isValidTransactionDate($date))
            ->each(fn (Carbon $date) => $this->createTransactionIfNotExists($recurringTransaction, $date));
    }

    private function defineGenerationPeriod(RecurringTransaction $recurringTransaction, int $monthsAhead): CarbonPeriod
    {
        $startMonth = $recurringTransaction->start_date->isFuture()
            ? $recurringTransaction->start_date->copy()->startOfMonth()
            : Carbon::today()->startOfMonth();

        return CarbonPeriod::since($startMonth)
            ->months(1)
            ->until($startMonth->copy()->addMonthsNoOverflow($monthsAhead));
    }

    private function createTransactionIfNotExists(RecurringTransaction $recurringTransaction, Carbon $transactionDate): void
    {
        $exists = $recurringTransaction->transactions()
            ->whereYear('transaction_date', $transactionDate->year)
            ->whereMonth('transaction_date', $transactionDate->month)
            ->exists();

        if ($exists) {
            return;
        }

        try {
            $recurringTransaction->transactions()->create([
                'user_id'          => $recurringTransaction->user_id,
                'category_id'      => $recurringTransaction->category_id,
                'tag_id'           => $recurringTransaction->tag_id,
                'amount'           => $recurringTransaction->amount,
                'type'             => $recurringTransaction->type,
                'description'      => $recurringTransaction->description,
                'transaction_date' => $transactionDate,
                'notes'            => 'Automatically generated by the recurring transaction',
            ]);
            Log::info('Recurring transaction generated successfully.', [
                'recurring_id' => $recurringTransaction->id,
                'user_id'      => $recurringTransaction->user_id,
                'date'         => $transactionDate->toDateString(),
            ]);
        } catch (Exception $e) {
            Log::error('Failed to generate recurring transaction.', [
                'recurring_id' => $recurringTransaction->id,
                'user_id'      => $recurringTransaction->user_id,
                'date'         => $transactionDate->toDateString(),
                'error'        => $e->getMessage(),
            ]);
        }
    }
}
